### ISSUE TITLE
add support for Dovetail Omni-C/DNASE

### ISSUE THREAD

**Issue by mcshane** [wtsi-hpag/HiLine#1]

**Comment by EdHarry** [comment]
Hi Shane,

I've added omni-c (and DNASE) options in a test branch https://github.com/wtsi-hpag/HiLine/tree/no_enzymes

This is quite a big change since all the restriction fragment logic is now being bypassed. I've tested on a small example, but would you mind beta-testing to make sure it's suitable for your needs?
